# Generated by Django 4.2.5 on 2023-10-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_listing_listing_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CAR', 'Vehicles'), ('PRP', 'Properties'), ('CLO', 'Clothes'), ('ELE', 'Electronics'), ('JOB', 'Jobs'), ('ANI', 'Animals'), ('SPO', 'Sports')], default='CAR', max_length=3),
        ),
    ]
