# Generated by Django 4.2.5 on 2023-10-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_current_price_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Vehicles', 'Vehicles'), ('Properties', 'Properties'), ('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Jobs', 'Jobs'), ('Animals', 'Animals'), ('Sports', 'Sports')], default='Vehicles', max_length=16),
        ),
    ]
