# Generated by Django 4.2.5 on 2023-10-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_description_alter_listing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Vehicles', 'Vehicles'), ('Properties', 'Properties'), ('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Animals', 'Animals'), ('Sports', 'Sports'), ('Others', 'Others')], default='Vehicles', max_length=16),
        ),
    ]
