# Generated by Django 4.2.5 on 2023-10-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comment_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.AddField(
            model_name='listing',
            name='last_bidder_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
