# Generated by Django 4.2.5 on 2023-10-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_bid_auction_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
    ]
